/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.22
 * Generated at: 2014-03-24 18:03:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.konakart.al.ProductMgr;
import com.konakart.app.DataDescConstants;

public final class ProductsBody_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/kk.tld", Long.valueOf(1394734414000L));
    _jspx_dependants.put("/WEB-INF/jsp/Taglibs.jsp", Long.valueOf(1394734414000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fkk_005fpageSize_0026_005ftimestamp_005fsizes_005fname_005fmaxNum_005faction_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fkk_005fpaging_0026_005ftimestamp_005fshowNext_005fshowBack_005fpageList_005fcurrentPage_005faction_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fkk_005fprodTile_0026_005fprod_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fkk_005fpageSize_0026_005ftimestamp_005fsizes_005fname_005fmaxNum_005faction_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fkk_005fpaging_0026_005ftimestamp_005fshowNext_005fshowBack_005fpageList_005fcurrentPage_005faction_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fkk_005fprodTile_0026_005fprod_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.release();
    _005fjspx_005ftagPool_005fkk_005fpageSize_0026_005ftimestamp_005fsizes_005fname_005fmaxNum_005faction_005fnobody.release();
    _005fjspx_005ftagPool_005fkk_005fpaging_0026_005ftimestamp_005fshowNext_005fshowBack_005fpageList_005fcurrentPage_005faction_005fnobody.release();
    _005fjspx_005ftagPool_005fkk_005fprodTile_0026_005fprod_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 com.konakart.al.KKAppEng kkEng = (com.konakart.al.KKAppEng) session.getAttribute("konakartKey");  
      out.write('\r');
      out.write('\n');
 com.konakart.al.ProductMgr prodMgr = kkEng.getProductMgr();
      out.write('\r');
      out.write('\n');
 com.konakart.appif.ProductIf[] prodArray = prodMgr.getCurrentProducts();
      out.write('\r');
      out.write('\n');
 com.konakart.appif.CategoryIf currentCat = prodMgr.getSelectedCategory();
      out.write('\r');
      out.write('\n');
 com.konakart.appif.ManufacturerIf currentManu = prodMgr.getSelectedManufacturer();
      out.write('\r');
      out.write('\n');
 String sortBy = prodMgr.getDataDesc().getOrderBy();
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" ");
if (prodArray == null || prodArray.length == 0){ 
      out.write("\r\n");
      out.write("   \t\t<div id=\"item-overview\" class=\"item-area ");
      out.print(kkEng.getContentClass());
      out.write(" rounded-corners\">\r\n");
      out.write("\t\t\t<div class=\"item-area-header\"></div>\r\n");
      out.write("\t\t\t<div class=\"items\">\t\r\n");
      out.write("\t\t\t\t\t");
if (prodMgr.isExpiredResultSet()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_kk_005fmsg_005f0(_jspx_page_context))
        return;
      out.write(".\r\n");
      out.write("\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_kk_005fmsg_005f1(_jspx_page_context))
        return;
      out.write(".\t    \t\t\t\t\t\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"item-area-footer\"></div>\r\n");
      out.write("\t\t</div>\r\n");
 } else { 
      out.write("\r\n");
      out.write(" \t    \t\t<div id=\"item-overview\" class=\"item-area ");
      out.print(kkEng.getContentClass());
      out.write(" rounded-corners\">\r\n");
      out.write("\t\t\t\t\t<div class=\"item-area-header\">\r\n");
      out.write("\t    \t\t\t\t<div class=\"item-overview-area-navigation\">\r\n");
      out.write("\t    \t\t\t\t\t<div class=\"item-overview-area-navigation-left\">\r\n");
      out.write("\t\t    \t\t\t\t\t<span class=\"number-of-items navigation-element\">\r\n");
      out.write("\t\t    \t\t\t\t\t");
      out.print(prodMgr.getCurrentOffset() + 1);
      out.write('-');
      out.print(prodMgr.getNumberOfProducts() + prodMgr.getCurrentOffset());
      out.write(' ');
      if (_jspx_meth_kk_005fmsg_005f2(_jspx_page_context))
        return;
      out.write(' ');
      out.print(prodMgr.getTotalNumberOfProducts());
      out.write(' ');
      if (_jspx_meth_kk_005fmsg_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t    \t\t\t\t\t</span>\r\n");
      out.write("\t\t\t    \t\t\t\t<span class=\"separator\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"sort-by navigation-element navigation-dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<form action=\"SortProd.action\" method=\"post\">");
      if (_jspx_meth_kk_005fmsg_005f4(_jspx_page_context))
        return;
      out.write(":\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<select name=\"orderBy\" onchange=\"submit()\">\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option  value=\"");
      out.print(DataDescConstants.ORDER_BY_TIMES_VIEWED_DESCENDING);
      out.write('"');
      out.write(' ');
      out.print((sortBy.equals(DataDescConstants.ORDER_BY_TIMES_VIEWED_DESCENDING)?"selected=\"selected\"":"") );
      out.write('>');
      if (_jspx_meth_kk_005fmsg_005f5(_jspx_page_context))
        return;
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option  value=\"");
      out.print(DataDescConstants.ORDER_BY_TIMES_ORDERED_DESCENDING);
      out.write('"');
      out.write(' ');
      out.print((sortBy.equals(DataDescConstants.ORDER_BY_TIMES_ORDERED_DESCENDING)?"selected=\"selected\"":"") );
      out.write('>');
      if (_jspx_meth_kk_005fmsg_005f6(_jspx_page_context))
        return;
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option  value=\"");
      out.print(DataDescConstants.ORDER_BY_PRICE_ASCENDING);
      out.write('"');
      out.write(' ');
      out.print((sortBy.equals(DataDescConstants.ORDER_BY_PRICE_ASCENDING)?"selected=\"selected\"":"") );
      out.write('>');
      if (_jspx_meth_kk_005fmsg_005f7(_jspx_page_context))
        return;
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option  value=\"");
      out.print(DataDescConstants.ORDER_BY_PRICE_DESCENDING);
      out.write('"');
      out.write(' ');
      out.print((sortBy.equals(DataDescConstants.ORDER_BY_PRICE_DESCENDING)?"selected=\"selected\"":"") );
      out.write('>');
      if (_jspx_meth_kk_005fmsg_005f8(_jspx_page_context))
        return;
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option  value=\"");
      out.print(DataDescConstants.ORDER_BY_RATING_DESCENDING);
      out.write('"');
      out.write(' ');
      out.print((sortBy.equals(DataDescConstants.ORDER_BY_RATING_DESCENDING)?"selected=\"selected\"":"") );
      out.write('>');
      if (_jspx_meth_kk_005fmsg_005f9(_jspx_page_context))
        return;
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"t\" value=\"");
      out.print(prodMgr.getProdTimestamp());
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</form>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"item-overview-area-navigation-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      //  kk:pageSize
      com.konakart.kktags.PageSizeTag _jspx_th_kk_005fpageSize_005f0 = (com.konakart.kktags.PageSizeTag) _005fjspx_005ftagPool_005fkk_005fpageSize_0026_005ftimestamp_005fsizes_005fname_005fmaxNum_005faction_005fnobody.get(com.konakart.kktags.PageSizeTag.class);
      _jspx_th_kk_005fpageSize_005f0.setPageContext(_jspx_page_context);
      _jspx_th_kk_005fpageSize_005f0.setParent(null);
      // /WEB-INF/jsp/ProductsBody.jsp(67,8) name = action type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fpageSize_005f0.setAction("ProdPageSize.action");
      // /WEB-INF/jsp/ProductsBody.jsp(67,8) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fpageSize_005f0.setName("numProds");
      // /WEB-INF/jsp/ProductsBody.jsp(67,8) name = sizes type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fpageSize_005f0.setSizes("8,12,16,20,24,28");
      // /WEB-INF/jsp/ProductsBody.jsp(67,8) name = maxNum type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fpageSize_005f0.setMaxNum(prodMgr.getMaxDisplaySearchResults());
      // /WEB-INF/jsp/ProductsBody.jsp(67,8) name = timestamp type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fpageSize_005f0.setTimestamp(prodMgr.getProdTimestamp());
      int _jspx_eval_kk_005fpageSize_005f0 = _jspx_th_kk_005fpageSize_005f0.doStartTag();
      if (_jspx_th_kk_005fpageSize_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fkk_005fpageSize_0026_005ftimestamp_005fsizes_005fname_005fmaxNum_005faction_005fnobody.reuse(_jspx_th_kk_005fpageSize_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fkk_005fpageSize_0026_005ftimestamp_005fsizes_005fname_005fmaxNum_005faction_005fnobody.reuse(_jspx_th_kk_005fpageSize_005f0);
      out.write("\r\n");
      out.write("\t\t\t    \t\t\t\t<span class=\"separator\"></span>\r\n");
      out.write("\t\t\t    \t\t\t\t");
      //  kk:paging
      com.konakart.kktags.PagingTag _jspx_th_kk_005fpaging_005f0 = (com.konakart.kktags.PagingTag) _005fjspx_005ftagPool_005fkk_005fpaging_0026_005ftimestamp_005fshowNext_005fshowBack_005fpageList_005fcurrentPage_005faction_005fnobody.get(com.konakart.kktags.PagingTag.class);
      _jspx_th_kk_005fpaging_005f0.setPageContext(_jspx_page_context);
      _jspx_th_kk_005fpaging_005f0.setParent(null);
      // /WEB-INF/jsp/ProductsBody.jsp(69,11) name = pageList type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fpaging_005f0.setPageList(prodMgr.getPageList());
      // /WEB-INF/jsp/ProductsBody.jsp(69,11) name = currentPage type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fpaging_005f0.setCurrentPage(prodMgr.getCurrentPage());
      // /WEB-INF/jsp/ProductsBody.jsp(69,11) name = showBack type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fpaging_005f0.setShowBack(prodMgr.getShowBack());
      // /WEB-INF/jsp/ProductsBody.jsp(69,11) name = showNext type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fpaging_005f0.setShowNext(prodMgr.getShowNext());
      // /WEB-INF/jsp/ProductsBody.jsp(69,11) name = action type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fpaging_005f0.setAction("NavigateProd");
      // /WEB-INF/jsp/ProductsBody.jsp(69,11) name = timestamp type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fpaging_005f0.setTimestamp(prodMgr.getProdTimestamp());
      int _jspx_eval_kk_005fpaging_005f0 = _jspx_th_kk_005fpaging_005f0.doStartTag();
      if (_jspx_th_kk_005fpaging_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fkk_005fpaging_0026_005ftimestamp_005fshowNext_005fshowBack_005fpageList_005fcurrentPage_005faction_005fnobody.reuse(_jspx_th_kk_005fpaging_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fkk_005fpaging_0026_005ftimestamp_005fshowNext_005fshowBack_005fpageList_005fcurrentPage_005faction_005fnobody.reuse(_jspx_th_kk_005fpaging_005f0);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t    \t\t\t\t</div>\r\n");
      out.write("\t    \t\t\t</div>\r\n");
      out.write("\t    \t\t\t<div class=\"items\">\t    \t\t\t\r\n");
      out.write("\t\t    \t\t\t<div class=\"item-row\">\r\n");
      out.write("\t\t    \t\t\t\t");
int numProds =  (prodArray.length > prodMgr.getMaxDisplaySearchResults()) ? prodMgr.getMaxDisplaySearchResults() : prodArray.length;
      out.write("\r\n");
      out.write("\t\t \t\t\t\t\t");
 for (int i = 0; i < numProds; i++){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 com.konakart.appif.ProductIf prod = prodArray[i];
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
if ( i%4 == 0 && i != 0) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t </div><div class=\"item-row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      //  kk:prodTile
      com.konakart.kktags.ProdTileTag _jspx_th_kk_005fprodTile_005f0 = (com.konakart.kktags.ProdTileTag) _005fjspx_005ftagPool_005fkk_005fprodTile_0026_005fprod_005fnobody.get(com.konakart.kktags.ProdTileTag.class);
      _jspx_th_kk_005fprodTile_005f0.setPageContext(_jspx_page_context);
      _jspx_th_kk_005fprodTile_005f0.setParent(null);
      // /WEB-INF/jsp/ProductsBody.jsp(81,9) name = prod type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fprodTile_005f0.setProd(prod);
      int _jspx_eval_kk_005fprodTile_005f0 = _jspx_th_kk_005fprodTile_005f0.doStartTag();
      if (_jspx_th_kk_005fprodTile_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fkk_005fprodTile_0026_005fprod_005fnobody.reuse(_jspx_th_kk_005fprodTile_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fkk_005fprodTile_0026_005fprod_005fnobody.reuse(_jspx_th_kk_005fprodTile_005f0);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t    \t\t\t</div>\r\n");
      out.write("\t    \t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t       \t\t\t<div class=\"item-area-footer\">\r\n");
      out.write("\t    \t\t\t\t<div class=\"item-overview-area-navigation\">\r\n");
      out.write("\t    \t\t\t\t\t<div class=\"item-overview-area-navigation-left\">\r\n");
      out.write("\t\t    \t\t\t\t\t<span class=\"number-of-items navigation-element\">\r\n");
      out.write("\t\t    \t\t\t\t\t");
      out.print(prodMgr.getCurrentOffset() + 1);
      out.write('-');
      out.print(prodMgr.getNumberOfProducts() + prodMgr.getCurrentOffset());
      out.write(' ');
      if (_jspx_meth_kk_005fmsg_005f10(_jspx_page_context))
        return;
      out.write(' ');
      out.print(prodMgr.getTotalNumberOfProducts());
      out.write(' ');
      if (_jspx_meth_kk_005fmsg_005f11(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t    \t\t\t\t\t</span>\r\n");
      out.write("\t\t\t    \t\t\t\t<span class=\"separator\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"sort-by navigation-element navigation-dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<form action=\"SortProd.action\" method=\"post\">");
      if (_jspx_meth_kk_005fmsg_005f12(_jspx_page_context))
        return;
      out.write(":\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<select name=\"orderBy\" onchange=\"submit()\">\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option  value=\"");
      out.print(DataDescConstants.ORDER_BY_TIMES_VIEWED_DESCENDING);
      out.write('"');
      out.write(' ');
      out.print((sortBy.equals(DataDescConstants.ORDER_BY_TIMES_VIEWED_DESCENDING)?"selected=\"selected\"":"") );
      out.write('>');
      if (_jspx_meth_kk_005fmsg_005f13(_jspx_page_context))
        return;
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option  value=\"");
      out.print(DataDescConstants.ORDER_BY_TIMES_ORDERED_DESCENDING);
      out.write('"');
      out.write(' ');
      out.print((sortBy.equals(DataDescConstants.ORDER_BY_TIMES_ORDERED_DESCENDING)?"selected=\"selected\"":"") );
      out.write('>');
      if (_jspx_meth_kk_005fmsg_005f14(_jspx_page_context))
        return;
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option  value=\"");
      out.print(DataDescConstants.ORDER_BY_PRICE_ASCENDING);
      out.write('"');
      out.write(' ');
      out.print((sortBy.equals(DataDescConstants.ORDER_BY_PRICE_ASCENDING)?"selected=\"selected\"":"") );
      out.write('>');
      if (_jspx_meth_kk_005fmsg_005f15(_jspx_page_context))
        return;
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option  value=\"");
      out.print(DataDescConstants.ORDER_BY_PRICE_DESCENDING);
      out.write('"');
      out.write(' ');
      out.print((sortBy.equals(DataDescConstants.ORDER_BY_PRICE_DESCENDING)?"selected=\"selected\"":"") );
      out.write('>');
      if (_jspx_meth_kk_005fmsg_005f16(_jspx_page_context))
        return;
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option  value=\"");
      out.print(DataDescConstants.ORDER_BY_RATING_DESCENDING);
      out.write('"');
      out.write(' ');
      out.print((sortBy.equals(DataDescConstants.ORDER_BY_RATING_DESCENDING)?"selected=\"selected\"":"") );
      out.write('>');
      if (_jspx_meth_kk_005fmsg_005f17(_jspx_page_context))
        return;
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"t\" value=\"");
      out.print(prodMgr.getProdTimestamp());
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</form>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"item-overview-area-navigation-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      //  kk:pageSize
      com.konakart.kktags.PageSizeTag _jspx_th_kk_005fpageSize_005f1 = (com.konakart.kktags.PageSizeTag) _005fjspx_005ftagPool_005fkk_005fpageSize_0026_005ftimestamp_005fsizes_005fname_005fmaxNum_005faction_005fnobody.get(com.konakart.kktags.PageSizeTag.class);
      _jspx_th_kk_005fpageSize_005f1.setPageContext(_jspx_page_context);
      _jspx_th_kk_005fpageSize_005f1.setParent(null);
      // /WEB-INF/jsp/ProductsBody.jsp(107,8) name = action type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fpageSize_005f1.setAction("ProdPageSize.action");
      // /WEB-INF/jsp/ProductsBody.jsp(107,8) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fpageSize_005f1.setName("numProds");
      // /WEB-INF/jsp/ProductsBody.jsp(107,8) name = sizes type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fpageSize_005f1.setSizes("8,12,16,20,24,28");
      // /WEB-INF/jsp/ProductsBody.jsp(107,8) name = maxNum type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fpageSize_005f1.setMaxNum(prodMgr.getMaxDisplaySearchResults());
      // /WEB-INF/jsp/ProductsBody.jsp(107,8) name = timestamp type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fpageSize_005f1.setTimestamp(prodMgr.getProdTimestamp());
      int _jspx_eval_kk_005fpageSize_005f1 = _jspx_th_kk_005fpageSize_005f1.doStartTag();
      if (_jspx_th_kk_005fpageSize_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fkk_005fpageSize_0026_005ftimestamp_005fsizes_005fname_005fmaxNum_005faction_005fnobody.reuse(_jspx_th_kk_005fpageSize_005f1);
        return;
      }
      _005fjspx_005ftagPool_005fkk_005fpageSize_0026_005ftimestamp_005fsizes_005fname_005fmaxNum_005faction_005fnobody.reuse(_jspx_th_kk_005fpageSize_005f1);
      out.write("\r\n");
      out.write("\t\t\t    \t\t\t\t<span class=\"separator\"></span>\r\n");
      out.write("\t\t\t    \t\t\t\t");
      //  kk:paging
      com.konakart.kktags.PagingTag _jspx_th_kk_005fpaging_005f1 = (com.konakart.kktags.PagingTag) _005fjspx_005ftagPool_005fkk_005fpaging_0026_005ftimestamp_005fshowNext_005fshowBack_005fpageList_005fcurrentPage_005faction_005fnobody.get(com.konakart.kktags.PagingTag.class);
      _jspx_th_kk_005fpaging_005f1.setPageContext(_jspx_page_context);
      _jspx_th_kk_005fpaging_005f1.setParent(null);
      // /WEB-INF/jsp/ProductsBody.jsp(109,11) name = pageList type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fpaging_005f1.setPageList(prodMgr.getPageList());
      // /WEB-INF/jsp/ProductsBody.jsp(109,11) name = currentPage type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fpaging_005f1.setCurrentPage(prodMgr.getCurrentPage());
      // /WEB-INF/jsp/ProductsBody.jsp(109,11) name = showBack type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fpaging_005f1.setShowBack(prodMgr.getShowBack());
      // /WEB-INF/jsp/ProductsBody.jsp(109,11) name = showNext type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fpaging_005f1.setShowNext(prodMgr.getShowNext());
      // /WEB-INF/jsp/ProductsBody.jsp(109,11) name = action type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fpaging_005f1.setAction("NavigateProd");
      // /WEB-INF/jsp/ProductsBody.jsp(109,11) name = timestamp type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fpaging_005f1.setTimestamp(prodMgr.getProdTimestamp());
      int _jspx_eval_kk_005fpaging_005f1 = _jspx_th_kk_005fpaging_005f1.doStartTag();
      if (_jspx_th_kk_005fpaging_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fkk_005fpaging_0026_005ftimestamp_005fshowNext_005fshowBack_005fpageList_005fcurrentPage_005faction_005fnobody.reuse(_jspx_th_kk_005fpaging_005f1);
        return;
      }
      _005fjspx_005ftagPool_005fkk_005fpaging_0026_005ftimestamp_005fshowNext_005fshowBack_005fpageList_005fcurrentPage_005faction_005fnobody.reuse(_jspx_th_kk_005fpaging_005f1);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t    \t\t\t\t</div>\r\n");
      out.write("\t    \t\t\t</div>\r\n");
      out.write("\t    \t\t</div>\r\n");
      out.write("\r\n");
 } 
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_kk_005fmsg_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f0 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f0.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f0.setParent(null);
    // /WEB-INF/jsp/ProductsBody.jsp(37,5) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f0.setKey("products.body.products.have.expired");
    int _jspx_eval_kk_005fmsg_005f0 = _jspx_th_kk_005fmsg_005f0.doStartTag();
    if (_jspx_th_kk_005fmsg_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f0);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f1 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f1.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f1.setParent(null);
    // /WEB-INF/jsp/ProductsBody.jsp(39,5) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f1.setKey("products.body.there.are.no.products.to.list.in.this.category");
    int _jspx_eval_kk_005fmsg_005f1 = _jspx_th_kk_005fmsg_005f1.doStartTag();
    if (_jspx_th_kk_005fmsg_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f1);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f2 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f2.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f2.setParent(null);
    // /WEB-INF/jsp/ProductsBody.jsp(50,111) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f2.setKey("common.of");
    int _jspx_eval_kk_005fmsg_005f2 = _jspx_th_kk_005fmsg_005f2.doStartTag();
    if (_jspx_th_kk_005fmsg_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f2);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f3 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f3.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f3.setParent(null);
    // /WEB-INF/jsp/ProductsBody.jsp(50,178) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f3.setKey("products.body.products");
    int _jspx_eval_kk_005fmsg_005f3 = _jspx_th_kk_005fmsg_005f3.doStartTag();
    if (_jspx_th_kk_005fmsg_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f3);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f4 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f4.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f4.setParent(null);
    // /WEB-INF/jsp/ProductsBody.jsp(54,54) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f4.setKey("common.sort.by");
    int _jspx_eval_kk_005fmsg_005f4 = _jspx_th_kk_005fmsg_005f4.doStartTag();
    if (_jspx_th_kk_005fmsg_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f4);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f5 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f5.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f5.setParent(null);
    // /WEB-INF/jsp/ProductsBody.jsp(56,185) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f5.setKey("products.body.sort.products.by.most.viewed");
    int _jspx_eval_kk_005fmsg_005f5 = _jspx_th_kk_005fmsg_005f5.doStartTag();
    if (_jspx_th_kk_005fmsg_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f5);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f6 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f6.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f6.setParent(null);
    // /WEB-INF/jsp/ProductsBody.jsp(57,187) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f6.setKey("products.body.sort.products.by.most.sold");
    int _jspx_eval_kk_005fmsg_005f6 = _jspx_th_kk_005fmsg_005f6.doStartTag();
    if (_jspx_th_kk_005fmsg_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f6);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f7 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f7.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f7.setParent(null);
    // /WEB-INF/jsp/ProductsBody.jsp(58,169) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f7.setKey("products.body.sort.products.by.price.asc");
    int _jspx_eval_kk_005fmsg_005f7 = _jspx_th_kk_005fmsg_005f7.doStartTag();
    if (_jspx_th_kk_005fmsg_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f7);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f7);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f8 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f8.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f8.setParent(null);
    // /WEB-INF/jsp/ProductsBody.jsp(59,171) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f8.setKey("products.body.sort.products.by.price.desc");
    int _jspx_eval_kk_005fmsg_005f8 = _jspx_th_kk_005fmsg_005f8.doStartTag();
    if (_jspx_th_kk_005fmsg_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f8);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f8);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f9 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f9.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f9.setParent(null);
    // /WEB-INF/jsp/ProductsBody.jsp(60,173) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f9.setKey("products.body.sort.products.by.rating");
    int _jspx_eval_kk_005fmsg_005f9 = _jspx_th_kk_005fmsg_005f9.doStartTag();
    if (_jspx_th_kk_005fmsg_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f9);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f9);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f10 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f10.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f10.setParent(null);
    // /WEB-INF/jsp/ProductsBody.jsp(90,111) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f10.setKey("common.of");
    int _jspx_eval_kk_005fmsg_005f10 = _jspx_th_kk_005fmsg_005f10.doStartTag();
    if (_jspx_th_kk_005fmsg_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f10);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f10);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f11(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f11 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f11.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f11.setParent(null);
    // /WEB-INF/jsp/ProductsBody.jsp(90,178) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f11.setKey("products.body.products");
    int _jspx_eval_kk_005fmsg_005f11 = _jspx_th_kk_005fmsg_005f11.doStartTag();
    if (_jspx_th_kk_005fmsg_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f11);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f11);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f12(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f12 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f12.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f12.setParent(null);
    // /WEB-INF/jsp/ProductsBody.jsp(94,54) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f12.setKey("common.sort.by");
    int _jspx_eval_kk_005fmsg_005f12 = _jspx_th_kk_005fmsg_005f12.doStartTag();
    if (_jspx_th_kk_005fmsg_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f12);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f12);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f13(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f13 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f13.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f13.setParent(null);
    // /WEB-INF/jsp/ProductsBody.jsp(96,185) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f13.setKey("products.body.sort.products.by.most.viewed");
    int _jspx_eval_kk_005fmsg_005f13 = _jspx_th_kk_005fmsg_005f13.doStartTag();
    if (_jspx_th_kk_005fmsg_005f13.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f13);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f13);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f14(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f14 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f14.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f14.setParent(null);
    // /WEB-INF/jsp/ProductsBody.jsp(97,187) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f14.setKey("products.body.sort.products.by.most.sold");
    int _jspx_eval_kk_005fmsg_005f14 = _jspx_th_kk_005fmsg_005f14.doStartTag();
    if (_jspx_th_kk_005fmsg_005f14.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f14);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f14);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f15(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f15 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f15.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f15.setParent(null);
    // /WEB-INF/jsp/ProductsBody.jsp(98,169) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f15.setKey("products.body.sort.products.by.price.asc");
    int _jspx_eval_kk_005fmsg_005f15 = _jspx_th_kk_005fmsg_005f15.doStartTag();
    if (_jspx_th_kk_005fmsg_005f15.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f15);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f15);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f16(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f16 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f16.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f16.setParent(null);
    // /WEB-INF/jsp/ProductsBody.jsp(99,171) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f16.setKey("products.body.sort.products.by.price.desc");
    int _jspx_eval_kk_005fmsg_005f16 = _jspx_th_kk_005fmsg_005f16.doStartTag();
    if (_jspx_th_kk_005fmsg_005f16.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f16);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f16);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f17(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f17 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f17.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f17.setParent(null);
    // /WEB-INF/jsp/ProductsBody.jsp(100,173) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f17.setKey("products.body.sort.products.by.rating");
    int _jspx_eval_kk_005fmsg_005f17 = _jspx_th_kk_005fmsg_005f17.doStartTag();
    if (_jspx_th_kk_005fmsg_005f17.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f17);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f17);
    return false;
  }
}
