/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.22
 * Generated at: 2014-03-20 05:43:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class MainLayout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/kk.tld", Long.valueOf(1391230460000L));
    _jspx_dependants.put("/WEB-INF/jsp/Taglibs.jsp", Long.valueOf(1391230460000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftiles_005fuseAttribute_0026_005fname_005fignore_005fid_005fclassname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005furl_0026_005faction_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ftiles_005fuseAttribute_0026_005fname_005fignore_005fid_005fclassname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005furl_0026_005faction_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ftiles_005fuseAttribute_0026_005fname_005fignore_005fid_005fclassname_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005furl_0026_005faction_005fnobody.release();
    _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\"\r\n");
      out.write("\"http://www.w3.org/TR/html4/strict.dtd\">\r\n");
      out.write("\r\n");
 com.konakart.al.KKAppEng kkEng = (com.konakart.al.KKAppEng) session.getAttribute("konakartKey");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" ");
if (kkEng != null) {
      out.write("\r\n");
      out.write(" \t");
      //  tiles:useAttribute
      org.apache.tiles.jsp.taglib.UseAttributeTag _jspx_th_tiles_005fuseAttribute_005f0 = (org.apache.tiles.jsp.taglib.UseAttributeTag) _005fjspx_005ftagPool_005ftiles_005fuseAttribute_0026_005fname_005fignore_005fid_005fclassname_005fnobody.get(org.apache.tiles.jsp.taglib.UseAttributeTag.class);
      _jspx_th_tiles_005fuseAttribute_005f0.setPageContext(_jspx_page_context);
      _jspx_th_tiles_005fuseAttribute_005f0.setParent(null);
      // /WEB-INF/jsp/MainLayout.jsp(28,2) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005fuseAttribute_005f0.setId("contentClass");
      // /WEB-INF/jsp/MainLayout.jsp(28,2) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005fuseAttribute_005f0.setName("contentClass");
      // /WEB-INF/jsp/MainLayout.jsp(28,2) name = classname type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005fuseAttribute_005f0.setClassname("java.lang.String");
      // /WEB-INF/jsp/MainLayout.jsp(28,2) name = ignore type = boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005fuseAttribute_005f0.setIgnore(true);
      int _jspx_eval_tiles_005fuseAttribute_005f0 = _jspx_th_tiles_005fuseAttribute_005f0.doStartTag();
      if (_jspx_th_tiles_005fuseAttribute_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005ftiles_005fuseAttribute_0026_005fname_005fignore_005fid_005fclassname_005fnobody.reuse(_jspx_th_tiles_005fuseAttribute_005f0);
        return;
      }
      _005fjspx_005ftagPool_005ftiles_005fuseAttribute_0026_005fname_005fignore_005fid_005fclassname_005fnobody.reuse(_jspx_th_tiles_005fuseAttribute_005f0);
      java.lang.String contentClass = null;
      contentClass = (java.lang.String) _jspx_page_context.findAttribute("contentClass");
      out.write("\r\n");
      out.write("    ");
kkEng.setContentClass(contentClass);
      out.write("\r\n");
      out.write("    ");
 if (kkEng.getProductMgr().getCurrentCategoriesLength() == 0 && contentClass.equalsIgnoreCase("narrow")){
      out.write("\r\n");
      out.write("    \t");
kkEng.setContentClass("wide");
      out.write("\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");
      //  tiles:useAttribute
      org.apache.tiles.jsp.taglib.UseAttributeTag _jspx_th_tiles_005fuseAttribute_005f1 = (org.apache.tiles.jsp.taglib.UseAttributeTag) _005fjspx_005ftagPool_005ftiles_005fuseAttribute_0026_005fname_005fignore_005fid_005fclassname_005fnobody.get(org.apache.tiles.jsp.taglib.UseAttributeTag.class);
      _jspx_th_tiles_005fuseAttribute_005f1.setPageContext(_jspx_page_context);
      _jspx_th_tiles_005fuseAttribute_005f1.setParent(null);
      // /WEB-INF/jsp/MainLayout.jsp(34,4) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005fuseAttribute_005f1.setId("defName");
      // /WEB-INF/jsp/MainLayout.jsp(34,4) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005fuseAttribute_005f1.setName("defName");
      // /WEB-INF/jsp/MainLayout.jsp(34,4) name = classname type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005fuseAttribute_005f1.setClassname("java.lang.String");
      // /WEB-INF/jsp/MainLayout.jsp(34,4) name = ignore type = boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005fuseAttribute_005f1.setIgnore(true);
      int _jspx_eval_tiles_005fuseAttribute_005f1 = _jspx_th_tiles_005fuseAttribute_005f1.doStartTag();
      if (_jspx_th_tiles_005fuseAttribute_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005ftiles_005fuseAttribute_0026_005fname_005fignore_005fid_005fclassname_005fnobody.reuse(_jspx_th_tiles_005fuseAttribute_005f1);
        return;
      }
      _005fjspx_005ftagPool_005ftiles_005fuseAttribute_0026_005fname_005fignore_005fid_005fclassname_005fnobody.reuse(_jspx_th_tiles_005fuseAttribute_005f1);
      java.lang.String defName = null;
      defName = (java.lang.String) _jspx_page_context.findAttribute("defName");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");
if (kkEng.isPortlet()) {
      out.write("\r\n");
      out.write("\t    ");
request.getSession().setAttribute("konakartKey", kkEng); 
      out.write(" \r\n");
      out.write("\t    ");
kkEng.setPortletContextPath(request.getContextPath());
      out.write("\r\n");
      out.write("\t\t<input id=\"kk_portlet_id\" type=\"hidden\" value=\"");
      out.print(request.getAttribute("PORTLET_ID"));
      out.write("\"/>\r\n");
      out.write("\t\t<input id=\"kk_sample_url\" type=\"hidden\" value=\"");
      if (_jspx_meth_s_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"/>\r\n");
      out.write("\t\t<input id=\"kk_context\" type=\"hidden\" value=\"");
      out.print(request.getContextPath());
      out.write("\"/>\t\t\r\n");
      out.write("\t\t<div id=\"kk-portlet-body\">\t\t\r\n");
      out.write("    ");
 } else { 
      out.write("\r\n");
      out.write("\t\t<html>\r\n");
      out.write("\t\t\t<head>");
      out.write("\r\n");
      out.write("\t\t\t\t");
      out.write("<title>");
      out.print(kkEng.getPageTitle());
      out.write("</title>");
      out.write("\r\n");
      out.write("\t\t\t\t");
      out.write("<meta name=\"");
      out.write("keywords\"");
      out.write(" content=\"");
      out.print(kkEng.getMetaKeywords());
      out.write('"');
      out.write(' ');
      out.write('/');
      out.write(">\r\n");
      out.write("\t\t\t\t");
      out.write("<meta name=\"");
      out.write("description\"");
      out.write(" content=\"");
      out.print(kkEng.getMetaDescription());
      out.write('"');
      out.write(' ');
      out.write('/');
      out.write(">\r\n");
      out.write("\t\t\t\t");
      out.write("<meta http-equiv=\"");
      out.write("Content-Type\"");
      out.write(" content=\"");
      out.write("text/html; charset=UTF-8\"");
      out.write(' ');
      out.write('/');
      out.write(">\r\n");
      out.write("\t\t\t\t");

try {
  java.lang.Class __nrClass = Class.forName("com.newrelic.api.agent.NewRelicApiImplementation");
  java.lang.reflect.Method __nrMethod = __nrClass.getMethod("getBrowserTimingHeaderForContentType", new Class[]{ String.class });
  out.write((String) __nrMethod.invoke(null, new Object[]{ null }));
} catch (Throwable __t) {
}

      out.write("<link rel=\"stylesheet\" href=\"https://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/themes/base/jquery-ui.css\" />\r\n");
      out.write("\t\t\t\t<link type=\"text/css\" rel=\"stylesheet\" href=\"");
      out.print(kkEng.getStyleBase());
      out.write("/jquery.selectboxit.css\" />\r\n");
      out.write("\t\t\t\t<link type=\"text/css\" rel=\"stylesheet\" href=\"");
      out.print(kkEng.getStyleBase());
      out.write("/kk-style.css\" />\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t \t\t");
      out.write("<script type=\"text/javascript\" src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js\"></script>");
      out.write("  \r\n");
      out.write("\t\t\t\t");
      out.write("<script type=\"text/javascript\" src=\"https://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js\"></script>");
      out.write("\r\n");
      out.write("\t\t\t\t");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(kkEng.getScriptBase());
      out.write("/jquery.validate.min.js\"></script>");
      out.write("\r\n");
      out.write("\t\t\t\t");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(kkEng.getScriptBase());
      out.write("/jquery.json-2.3.min.js\"></script>");
      out.write("\r\n");
      out.write("\t\t\t\t");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(kkEng.getScriptBase());
      out.write("/jquery.tools.min.js\"></script>");
      out.write("\r\n");
      out.write("\t\t\t\t");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(kkEng.getScriptBase());
      out.write("/jquery.selectboxit.min.js\"></script>");
      out.write("\r\n");
      out.write("\t\t\t\t");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(kkEng.getScriptBase());
      out.write("/jquery.ui.datepicker-en.js\"></script>");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t\t");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(kkEng.getScriptBase());
      out.write("/jquery.ui.datepicker-de.js\"></script>");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t\t");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(kkEng.getScriptBase());
      out.write("/jquery.ui.datepicker-pt.js\"></script>");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t\t");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(kkEng.getScriptBase());
      out.write("/jquery.ui.datepicker-es.js\"></script>");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t\t");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(kkEng.getScriptBase());
      out.write("/ddpowerzoomer.js\">\r\n");
      out.write("\t\t\t\t/***********************************************\r\n");
      out.write("\t\t\t\t* Image Power Zoomer- (c) Dynamic Drive DHTML code library (www.dynamicdrive.com)\r\n");
      out.write("\t\t\t\t* This notice MUST stay intact for legal use\r\n");
      out.write("\t\t\t\t* Visit Dynamic Drive at http://www.dynamicdrive.com/ for this script and 100s more\r\n");
      out.write("\t\t\t\t***********************************************/\r\n");
      out.write("\t\t\t\t</script>");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t\t");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(kkEng.getScriptBase());
      out.write("/jquery.jcarousel.min.js\"></script>");
      out.write("\r\n");
      out.write("\t\t\t\t");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(kkEng.getScriptBase());
      out.write("/jquery.cookie.js\"></script>");
      out.write("\r\n");
      out.write("\t\t\t\t");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(kkEng.getScriptBase());
      out.write("/kk.js\"></script>");
      out.write("\t\r\n");
      out.write("\t\t\t\t");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(kkEng.getScriptBase());
      out.write("/kk.validation.js\"></script>");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t");

				// Set the base
				String scheme = pageContext.getRequest().getScheme()+"://";
				String server = pageContext.getRequest().getServerName();
				int port = pageContext.getRequest().getServerPort();
				String path = session.getServletContext().getContextPath();
				String base = scheme+server+((port==80)?"":":"+port)+path+"/";
				
      out.write("\r\n");
      out.write("\t\t\t\t<base href=\"");
      out.print(base);
      out.write("\"/>\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t");
      out.write("<!--- KonaKart v7.1.1.1.10247 -->");
      out.write("\r\n");
      out.write("\t\t\t</head>\r\n");
      out.write("\t\t\t");
if (defName != null) {
      out.write("\r\n");
      out.write("\t\t\t\t<body id=\"");
      out.print(defName);
      out.write("\">\r\n");
      out.write("\t\t\t");
} else {
      out.write("\r\n");
      out.write("\t\t\t\t<body>\r\n");
      out.write("\t\t\t");
}
      out.write('\r');
      out.write('\n');
      out.write('	');
}
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("<script language=\"JavaScript\" type=\"text/javascript\">\r\n");
      out.write("\t\tif (top.location != location) {\r\n");
      out.write("\t\t\t\t\ttop.location.href = document.location.href ;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t// Set jquery validation messages\r\n");
      out.write("\t\t\tjQuery.validator.messages = {\r\n");
      out.write("\t\t\t\t\tstate: '");
      out.print(kkEng.getMsg("jquery.validator.required"));
      out.write("',\r\n");
      out.write("\t\t\t\t\tcountry: '");
      out.print(kkEng.getMsg("jquery.validator.required"));
      out.write("',\r\n");
      out.write("\t\t\t\t\trequired: '");
      out.print(kkEng.getMsg("jquery.validator.required"));
      out.write("',\r\n");
      out.write("\t\t\t\t\tcreditcard: '");
      out.print(kkEng.getMsg("jquery.validator.creditcard"));
      out.write("',\r\n");
      out.write("\t\t\t\t\tdigits: '");
      out.print(kkEng.getMsg("jquery.validator.digits"));
      out.write("',\r\n");
      out.write("\t\t\t\t\tmaxlength: jQuery.validator.format('");
      out.print(kkEng.getMsg("jquery.validator.maxlength"));
      out.write(" {0} ");
      out.print(kkEng.getMsg("jquery.validator.maxlength1"));
      out.write("'),\r\n");
      out.write("\t\t\t\t\tminlength: jQuery.validator.format('");
      out.print(kkEng.getMsg("jquery.validator.minlength"));
      out.write(" {0} ");
      out.print(kkEng.getMsg("jquery.validator.minlength1"));
      out.write("'),\r\n");
      out.write("\t\t\t\t\texpirydate: '");
      out.print(kkEng.getMsg("jquery.validator.expiryMMYY"));
      out.write("',\r\n");
      out.write("\t\t\t\t\temail:\t'");
      out.print(kkEng.getMsg("jquery.validator.email"));
      out.write("',\r\n");
      out.write("\t\t\t\t\turl:\t'");
      out.print(kkEng.getMsg("jquery.validator.url"));
      out.write("',\r\n");
      out.write("\t\t\t\t\tnumber:\t'");
      out.print(kkEng.getMsg("jquery.validator.number"));
      out.write("',\r\n");
      out.write(" \t\t\t\t\tequalTo: '");
      out.print(kkEng.getMsg("jquery.validator.equalTo"));
      out.write("'\r\n");
      out.write("\t\t};\t\t \r\n");
      out.write("\t</script>");
      out.write("\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_tiles_005finsertAttribute_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_tiles_005finsertAttribute_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t    \t\t<div id=\"page-container\">\r\n");
      out.write("\t    \t\t\t<div id=\"page\" class=\"");
      if (_jspx_meth_tiles_005finsertAttribute_005f2(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_tiles_005finsertAttribute_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_tiles_005finsertAttribute_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_tiles_005finsertAttribute_005f5(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div id=\"content\" class=\"");
      out.print(kkEng.getContentClass());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_tiles_005finsertAttribute_005f6(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("\t\t\t\t\t \t\t");
      if (_jspx_meth_tiles_005finsertAttribute_005f7(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_tiles_005finsertAttribute_005f8(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_tiles_005finsertAttribute_005f9(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_tiles_005finsertAttribute_005f10(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_tiles_005finsertAttribute_005f11(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t    \t</div>\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_tiles_005finsertAttribute_005f12(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t    \t\t</div>\r\n");
      out.write("\t    \t\t</div>\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_tiles_005finsertAttribute_005f13(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t");
      out.print(kkEng.getAnalyticsCode());
      out.write("\r\n");
      out.write("    ");
if (!kkEng.isPortlet()) {
      out.write("\r\n");
      out.write("\t\t\t");

try {
  java.lang.Class __nrClass = Class.forName("com.newrelic.api.agent.NewRelicApiImplementation");
  java.lang.reflect.Method __nrMethod = __nrClass.getMethod("getBrowserTimingFooterForContentType", new Class[]{ String.class });
  out.write((String) __nrMethod.invoke(null, new Object[]{ null }));
} catch (Throwable __t) {
}

      out.write("</body>\r\n");
      out.write("\t\t</html>\r\n");
      out.write("\t");
} else {
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t");
}
      out.write('\r');
      out.write('\n');
}
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.apache.struts2.views.jsp.URLTag _jspx_th_s_005furl_005f0 = (org.apache.struts2.views.jsp.URLTag) _005fjspx_005ftagPool_005fs_005furl_0026_005faction_005fnobody.get(org.apache.struts2.views.jsp.URLTag.class);
    _jspx_th_s_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005furl_005f0.setParent(null);
    // /WEB-INF/jsp/MainLayout.jsp(40,49) name = action type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f0.setAction("KK_ACTION");
    int _jspx_eval_s_005furl_005f0 = _jspx_th_s_005furl_005f0.doStartTag();
    if (_jspx_th_s_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005furl_0026_005faction_005fnobody.reuse(_jspx_th_s_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005furl_0026_005faction_005fnobody.reuse(_jspx_th_s_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f0 = (org.apache.tiles.jsp.taglib.InsertAttributeTag) _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.get(org.apache.tiles.jsp.taglib.InsertAttributeTag.class);
    _jspx_th_tiles_005finsertAttribute_005f0.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005finsertAttribute_005f0.setParent(null);
    // /WEB-INF/jsp/MainLayout.jsp(115,4) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f0.setName("header1");
    int _jspx_eval_tiles_005finsertAttribute_005f0 = _jspx_th_tiles_005finsertAttribute_005f0.doStartTag();
    if (_jspx_th_tiles_005finsertAttribute_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f0);
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f1 = (org.apache.tiles.jsp.taglib.InsertAttributeTag) _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.get(org.apache.tiles.jsp.taglib.InsertAttributeTag.class);
    _jspx_th_tiles_005finsertAttribute_005f1.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005finsertAttribute_005f1.setParent(null);
    // /WEB-INF/jsp/MainLayout.jsp(116,4) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f1.setName("header2");
    int _jspx_eval_tiles_005finsertAttribute_005f1 = _jspx_th_tiles_005finsertAttribute_005f1.doStartTag();
    if (_jspx_th_tiles_005finsertAttribute_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f1);
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f2 = (org.apache.tiles.jsp.taglib.InsertAttributeTag) _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.get(org.apache.tiles.jsp.taglib.InsertAttributeTag.class);
    _jspx_th_tiles_005finsertAttribute_005f2.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005finsertAttribute_005f2.setParent(null);
    // /WEB-INF/jsp/MainLayout.jsp(118,30) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f2.setName("pageClass");
    int _jspx_eval_tiles_005finsertAttribute_005f2 = _jspx_th_tiles_005finsertAttribute_005f2.doStartTag();
    if (_jspx_th_tiles_005finsertAttribute_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f2);
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f3 = (org.apache.tiles.jsp.taglib.InsertAttributeTag) _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.get(org.apache.tiles.jsp.taglib.InsertAttributeTag.class);
    _jspx_th_tiles_005finsertAttribute_005f3.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005finsertAttribute_005f3.setParent(null);
    // /WEB-INF/jsp/MainLayout.jsp(119,6) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f3.setName("header3");
    int _jspx_eval_tiles_005finsertAttribute_005f3 = _jspx_th_tiles_005finsertAttribute_005f3.doStartTag();
    if (_jspx_th_tiles_005finsertAttribute_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f3);
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f4 = (org.apache.tiles.jsp.taglib.InsertAttributeTag) _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.get(org.apache.tiles.jsp.taglib.InsertAttributeTag.class);
    _jspx_th_tiles_005finsertAttribute_005f4.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005finsertAttribute_005f4.setParent(null);
    // /WEB-INF/jsp/MainLayout.jsp(120,6) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f4.setName("header4");
    int _jspx_eval_tiles_005finsertAttribute_005f4 = _jspx_th_tiles_005finsertAttribute_005f4.doStartTag();
    if (_jspx_th_tiles_005finsertAttribute_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f4);
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f5 = (org.apache.tiles.jsp.taglib.InsertAttributeTag) _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.get(org.apache.tiles.jsp.taglib.InsertAttributeTag.class);
    _jspx_th_tiles_005finsertAttribute_005f5.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005finsertAttribute_005f5.setParent(null);
    // /WEB-INF/jsp/MainLayout.jsp(121,6) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f5.setName("left1");
    int _jspx_eval_tiles_005finsertAttribute_005f5 = _jspx_th_tiles_005finsertAttribute_005f5.doStartTag();
    if (_jspx_th_tiles_005finsertAttribute_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f5);
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f6 = (org.apache.tiles.jsp.taglib.InsertAttributeTag) _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.get(org.apache.tiles.jsp.taglib.InsertAttributeTag.class);
    _jspx_th_tiles_005finsertAttribute_005f6.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005finsertAttribute_005f6.setParent(null);
    // /WEB-INF/jsp/MainLayout.jsp(123,7) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f6.setName("body1");
    int _jspx_eval_tiles_005finsertAttribute_005f6 = _jspx_th_tiles_005finsertAttribute_005f6.doStartTag();
    if (_jspx_th_tiles_005finsertAttribute_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f6);
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f7 = (org.apache.tiles.jsp.taglib.InsertAttributeTag) _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.get(org.apache.tiles.jsp.taglib.InsertAttributeTag.class);
    _jspx_th_tiles_005finsertAttribute_005f7.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005finsertAttribute_005f7.setParent(null);
    // /WEB-INF/jsp/MainLayout.jsp(124,8) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f7.setName("body2");
    int _jspx_eval_tiles_005finsertAttribute_005f7 = _jspx_th_tiles_005finsertAttribute_005f7.doStartTag();
    if (_jspx_th_tiles_005finsertAttribute_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f7);
      return true;
    }
    _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f7);
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f8 = (org.apache.tiles.jsp.taglib.InsertAttributeTag) _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.get(org.apache.tiles.jsp.taglib.InsertAttributeTag.class);
    _jspx_th_tiles_005finsertAttribute_005f8.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005finsertAttribute_005f8.setParent(null);
    // /WEB-INF/jsp/MainLayout.jsp(125,7) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f8.setName("body3");
    int _jspx_eval_tiles_005finsertAttribute_005f8 = _jspx_th_tiles_005finsertAttribute_005f8.doStartTag();
    if (_jspx_th_tiles_005finsertAttribute_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f8);
      return true;
    }
    _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f8);
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f9 = (org.apache.tiles.jsp.taglib.InsertAttributeTag) _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.get(org.apache.tiles.jsp.taglib.InsertAttributeTag.class);
    _jspx_th_tiles_005finsertAttribute_005f9.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005finsertAttribute_005f9.setParent(null);
    // /WEB-INF/jsp/MainLayout.jsp(126,7) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f9.setName("body4");
    int _jspx_eval_tiles_005finsertAttribute_005f9 = _jspx_th_tiles_005finsertAttribute_005f9.doStartTag();
    if (_jspx_th_tiles_005finsertAttribute_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f9);
      return true;
    }
    _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f9);
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f10 = (org.apache.tiles.jsp.taglib.InsertAttributeTag) _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.get(org.apache.tiles.jsp.taglib.InsertAttributeTag.class);
    _jspx_th_tiles_005finsertAttribute_005f10.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005finsertAttribute_005f10.setParent(null);
    // /WEB-INF/jsp/MainLayout.jsp(127,7) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f10.setName("body5");
    int _jspx_eval_tiles_005finsertAttribute_005f10 = _jspx_th_tiles_005finsertAttribute_005f10.doStartTag();
    if (_jspx_th_tiles_005finsertAttribute_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f10);
      return true;
    }
    _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f10);
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f11(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f11 = (org.apache.tiles.jsp.taglib.InsertAttributeTag) _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.get(org.apache.tiles.jsp.taglib.InsertAttributeTag.class);
    _jspx_th_tiles_005finsertAttribute_005f11.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005finsertAttribute_005f11.setParent(null);
    // /WEB-INF/jsp/MainLayout.jsp(128,7) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f11.setName("body6");
    int _jspx_eval_tiles_005finsertAttribute_005f11 = _jspx_th_tiles_005finsertAttribute_005f11.doStartTag();
    if (_jspx_th_tiles_005finsertAttribute_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f11);
      return true;
    }
    _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f11);
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f12(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f12 = (org.apache.tiles.jsp.taglib.InsertAttributeTag) _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.get(org.apache.tiles.jsp.taglib.InsertAttributeTag.class);
    _jspx_th_tiles_005finsertAttribute_005f12.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005finsertAttribute_005f12.setParent(null);
    // /WEB-INF/jsp/MainLayout.jsp(130,6) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f12.setName("footer1");
    int _jspx_eval_tiles_005finsertAttribute_005f12 = _jspx_th_tiles_005finsertAttribute_005f12.doStartTag();
    if (_jspx_th_tiles_005finsertAttribute_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f12);
      return true;
    }
    _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f12);
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f13(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f13 = (org.apache.tiles.jsp.taglib.InsertAttributeTag) _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.get(org.apache.tiles.jsp.taglib.InsertAttributeTag.class);
    _jspx_th_tiles_005finsertAttribute_005f13.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005finsertAttribute_005f13.setParent(null);
    // /WEB-INF/jsp/MainLayout.jsp(133,4) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f13.setName("footer2");
    int _jspx_eval_tiles_005finsertAttribute_005f13 = _jspx_th_tiles_005finsertAttribute_005f13.doStartTag();
    if (_jspx_th_tiles_005finsertAttribute_005f13.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f13);
      return true;
    }
    _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f13);
    return false;
  }
}
