/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.22
 * Generated at: 2014-02-26 23:04:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.math.BigDecimal;

public final class Facets_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/kk.tld", Long.valueOf(1391230460000L));
    _jspx_dependants.put("/WEB-INF/jsp/Taglibs.jsp", Long.valueOf(1391230460000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write('\n');
      out.write('\n');
 com.konakart.al.KKAppEng kkEng = (com.konakart.al.KKAppEng) session.getAttribute("konakartKey");  
      out.write('\n');
 com.konakart.al.ProductMgr prodMgr = kkEng.getProductMgr();
      out.write('\n');
 com.konakart.al.CategoryMgr catMgr = kkEng.getCategoryMgr();
      out.write('\n');
 boolean useSolr = kkEng.isUseSolr();
      out.write("\n");
      out.write("\n");
      out.write(" \n");
      out.write("\t");
if (prodMgr.getMinPrice() != null && prodMgr.getMaxPrice() != null && prodMgr.getMinPrice().compareTo(prodMgr.getMaxPrice()) != 0){
      out.write('\n');
      out.write('	');
      out.write('	');
BigDecimal minPrice = prodMgr.getMinPrice();
      out.write('\n');
      out.write('	');
      out.write('	');
BigDecimal maxPrice = prodMgr.getMaxPrice();
      out.write('\n');
      out.write('	');
      out.write('	');
BigDecimal taxMult = prodMgr.getTaxMultiplier();
      out.write('\n');
      out.write('	');
      out.write('	');
BigDecimal minFilterPrice = (prodMgr.getProdSearch().getPriceFrom()==null)?minPrice:prodMgr.getProdSearch().getPriceFrom();
      out.write('\n');
      out.write('	');
      out.write('	');
BigDecimal maxFilterPrice = (prodMgr.getProdSearch().getPriceTo()==null)?maxPrice:prodMgr.getProdSearch().getPriceTo();
      out.write("\n");
      out.write("\t\t\n");
      out.write("\t\t");
if (kkEng.displayPriceWithTax() && taxMult != null && !taxMult.equals(new BigDecimal(1))){
      out.write("\t\n");
      out.write("\t\t\t");
minPrice = minPrice.multiply(taxMult);
      out.write("\t\t\t\t\n");
      out.write("\t\t\t");
maxPrice = maxPrice.multiply(taxMult);
      out.write("\t\t\t\t\n");
      out.write("\t\t\t");
minFilterPrice = minFilterPrice.multiply(taxMult);
      out.write("\t\t\t\t\n");
      out.write("\t\t\t");
maxFilterPrice = maxFilterPrice.multiply(taxMult);
      out.write("\t\t\t\t\n");
      out.write("\t\t");
}
      out.write("\n");
      out.write("\n");
      out.write("\t\t");
 minPrice = ((kkEng.convertPrice(minPrice)).setScale(2,BigDecimal.ROUND_HALF_UP)).setScale(0,BigDecimal.ROUND_DOWN);
      out.write('\n');
      out.write('	');
      out.write('	');
 maxPrice = ((kkEng.convertPrice(maxPrice)).setScale(2,BigDecimal.ROUND_HALF_UP)).setScale(0,BigDecimal.ROUND_UP);
      out.write('\n');
      out.write('	');
      out.write('	');
 minFilterPrice = ((kkEng.convertPrice(minFilterPrice)).setScale(2,BigDecimal.ROUND_HALF_UP)).setScale(0,BigDecimal.ROUND_DOWN);
      out.write('\n');
      out.write('	');
      out.write('	');
 maxFilterPrice = ((kkEng.convertPrice(maxFilterPrice)).setScale(2,BigDecimal.ROUND_HALF_UP)).setScale(0,BigDecimal.ROUND_UP);
      out.write("\n");
      out.write("\t\t\n");
      out.write("\t\t");
String symbol = kkEng.getUserCurrency().getSymbolLeft();
      out.write('\n');
      out.write('	');
      out.write('	');
      out.write("<script>\n");
      out.write("\t\t    $(function() {\n");
      out.write("\t\t        $( \"#price-range-slider\" ).slider({\n");
      out.write("\t\t            range: true,\n");
      out.write("\t\t            min: ");
      out.print(minPrice);
      out.write(",\n");
      out.write("\t\t            max: ");
      out.print(maxPrice);
      out.write(",\n");
      out.write("\t\t            values: [ ");
      out.print(minFilterPrice);
      out.write(',');
      out.write(' ');
      out.print(maxFilterPrice);
      out.write(" ],\n");
      out.write("\t\t            slide: function( event, ui ) {\n");
      out.write("\t\t                $( \"#amount\" ).html( \"");
      out.print(symbol);
      out.write("\"+ui.values[ 0 ] + \" - \" + \"");
      out.print(symbol);
      out.write("\"+ui.values[ 1 ] );\n");
      out.write("\t\t            },\n");
      out.write("\t\t\t        stop: function( event, ui ) {\n");
      out.write("\t\t\t\t\t\tdocument.getElementById('priceFromStr').value = ui.values[ 0 ];\n");
      out.write("\t\t\t\t\t\tdocument.getElementById('priceToStr').value = ui.values[ 1 ];\n");
      out.write("\t\t\t\t\t\tdocument.getElementById('priceFilterForm').submit();\n");
      out.write("\t\t\t        }\n");
      out.write("\t\t        });\n");
      out.write("\t\t        $( \"#amount\" ).html(\"");
      out.print(symbol);
      out.write("\"+$( \"#price-range-slider\" ).slider( \"values\", 0 ) +\n");
      out.write("\t\t            \" - \" +\"");
      out.print(symbol);
      out.write("\"+ $( \"#price-range-slider\" ).slider( \"values\", 1 ) );\n");
      out.write("\t\t    });\n");
      out.write("\t\t</script>");
      out.write(' ');
      out.write('\n');
      out.write('	');
 } 
      out.write("\n");
      out.write("\t<div id=\"side-menu\">\t\n");
      out.write("  \t\t\t");
 if (prodMgr.getCurrentCategoriesLength() > 0){
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<div class=\"side-menu-section\">\n");
      out.write("\t\t\t\t\t<h1>");
      if (_jspx_meth_kk_005fmsg_005f0(_jspx_page_context))
        return;
      out.write("</h1>\n");
      out.write("\t\t\t\t\t<ul>\t\t\t\t\n");
      out.write("\t\t\t\t\t");
 for (int i = 0; i < prodMgr.getCurrentCategories().length; i++){ 
      out.write("\n");
      out.write("\t\t\t\t\t\t");
 com.konakart.appif.CategoryIf cat = prodMgr.getCurrentCategories()[i];
      out.write("\n");
      out.write("\t\t\t\t\t\t");
String name = (cat.getNumberOfProducts() < 0)? cat.getName(): cat.getName()+" ("+cat.getNumberOfProducts()+")"; 
      out.write("\n");
      out.write("\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t");
for (int j = 0; j < cat.getLevel(); j++){
      out.write("\n");
      out.write("\t\t\t\t\t\t\t");
      out.print("&nbsp;");
      out.write("\n");
      out.write("\t\t\t\t\t\t");
 }
      out.write("\n");
      out.write("\t\t\t\t\t\t");
String action;
      out.write("\n");
      out.write("\t\t\t\t\t\t");
if (prodMgr.getNumSelectedFilters() > 0 || prodMgr.isPriceFilter()){
      out.write("\n");
      out.write("\t\t\t\t\t\t\t");
action= "FilterSearchByCategory.action?catId=";
      out.write("\n");
      out.write("\t\t\t\t\t\t");
 } else { 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t");
action= "SelectCat.action?catId=";
      out.write("\n");
      out.write("\t\t\t\t\t\t");
 }
      out.write("\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t");
if ( cat.isSelected()) { 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<a href='");
      out.print(action+cat.getId()+"&t="+prodMgr.getProdTimestamp());
      out.write("'><span class=\"current-cat\">");
      out.print(name);
      out.write("</span></a>\n");
      out.write("\t\t\t\t\t\t");
 } else { 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<a href='");
      out.print(action+cat.getId()+"&t="+prodMgr.getProdTimestamp());
      out.write('\'');
      out.write('>');
      out.print(name);
      out.write("</a>\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t");

				boolean haveManus = prodMgr.getCurrentManufacturersLength() > 0;
				boolean havePriceFacets = prodMgr.getPriceFacets() != null && prodMgr.getPriceFacets().length > 0;
				boolean havePriceSlider = prodMgr.getMinPrice() != null && prodMgr.getMaxPrice() != null && prodMgr.getMinPrice().compareTo(prodMgr.getMaxPrice()) != 0;
				boolean haveFacets = prodMgr.getCurrentTagGroups() != null && prodMgr.getCurrentTagGroups().length > 0;				
				
      out.write("\n");
      out.write("\t\t\t\t");
if (haveManus || havePriceFacets || havePriceSlider || haveFacets){
      out.write("\n");
      out.write("\t\t\t\t\t<h1>\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_kk_005fmsg_005f1(_jspx_page_context))
        return;
      out.write("\t\n");
      out.write("\t\t\t\t\t</h1>\n");
      out.write("\t\t\t\t");
}
      out.write("\n");
      out.write("\t\t\t\t");
if (prodMgr.getNumSelectedFilters() > 0 || prodMgr.isPriceFilter()){
      out.write("\n");
      out.write("\t\t\t\t");
      out.write("<!-- //jk changed 2/18/2014 -->");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t");
      out.write("\n");
      out.write("\t\t\t\t\t<div id=\"remove-all\"><img  src=\"");
      out.print(kkEng.getLocalImageBase());
      out.write("/x-button.png\"><a href='");
      out.print("RemoveTags.action?t="+prodMgr.getProdTimestamp());
      out.write('\'');
      out.write('>');
      if (_jspx_meth_kk_005fmsg_005f2(_jspx_page_context))
        return;
      out.write("</a></div>\t\t\t\t\n");
      out.write("\t\t\t\t");
}
      out.write("\n");
      out.write("\t\t\t\t    \t\t\t\t\t\t\n");
      out.write("\t\t\t\t");
if (haveManus){ 
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"side-menu-section\">\n");
      out.write("\t\t\t\t\t\t<h2>");
      if (_jspx_meth_kk_005fmsg_005f3(_jspx_page_context))
        return;
      out.write("</h2>\t\n");
      out.write("\t\t\t\t\t\t<ul>\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t");
 for (int i = 0; i < prodMgr.getCurrentManufacturers().length; i++){ 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t");
 com.konakart.appif.ManufacturerIf manu = prodMgr.getCurrentManufacturers()[i];
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t");
String name = manu.getName()+" ("+manu.getNumberOfProducts()+")"; 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t");
if ( manu.isSelected()) { 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href='");
      out.print("FilterSearchByManufacturer.action?manuId="+manu.getId()+"&t="+prodMgr.getProdTimestamp());
      out.write("'><span class=\"selected\"></span>");
      out.print(name);
      out.write("</a></li>\t\n");
      out.write("\t\t\t\t\t\t\t\t");
 } else { 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href='");
      out.print("FilterSearchByManufacturer.action?manuId="+manu.getId()+"&t="+prodMgr.getProdTimestamp());
      out.write("'><span class=\"not-selected\"></span>");
      out.print(name);
      out.write("</a></li>\t\n");
      out.write("\t\t\t\t\t\t\t\t");
 } 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t");
 } 
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t");
if (havePriceFacets){
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"side-menu-section\">\n");
      out.write("\t\t\t\t\t\t<h2>");
      if (_jspx_meth_kk_005fmsg_005f4(_jspx_page_context))
        return;
      out.write("</h2>\t\n");
      out.write("\t\t\t\t\t\t<ul>\t\n");
      out.write("\t\t\t\t\t\t\t");
BigDecimal taxMult = prodMgr.getTaxMultiplier();
      out.write("\t\t\t\n");
      out.write("\t\t\t\t\t\t\t");
 for (int i = 0; i < prodMgr.getPriceFacets().length; i++){ 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t");
 com.konakart.appif.KKPriceFacetIf pf = prodMgr.getPriceFacets()[i];
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t");
BigDecimal lowerLimit =pf.getLowerLimit();
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t");
BigDecimal upperLimit =pf.getUpperLimit();
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t");
if (kkEng.displayPriceWithTax() && taxMult != null && !taxMult.equals(new BigDecimal(1))){
      out.write("\t\n");
      out.write("\t\t\t\t\t\t\t\t\t");
lowerLimit = lowerLimit.multiply(taxMult);
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t");
upperLimit = upperLimit.multiply(taxMult);
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t");
}
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t");
String name = kkEng.convertPrice(lowerLimit).setScale(0,BigDecimal.ROUND_HALF_DOWN)+" - "+kkEng.convertPrice(upperLimit).setScale(0,BigDecimal.ROUND_HALF_UP) + " ("+pf.getNumProds()+")"; 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t");
if (pf.isSelected()) { 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href='");
      out.print("FilterSearchByPrice.action?from="+pf.getLowerLimit()+"&to="+pf.getUpperLimit()+"&t="+prodMgr.getProdTimestamp());
      out.write("'><span class=\"selected\"></span>");
      out.print(name);
      out.write("</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t");
 } else { 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href='");
      out.print("FilterSearchByPrice.action?from="+pf.getLowerLimit()+"&to="+pf.getUpperLimit()+"&t="+prodMgr.getProdTimestamp());
      out.write("'><span class=\"not-selected\"></span>");
      out.print(name);
      out.write("</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t");
 } 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t");
 } else if (havePriceSlider){
      out.write("\n");
      out.write("\t\t\t\t\t<div id=\"price\" class=\"range-slider\">\n");
      out.write("\t\t    \t\t\t<h2>");
      if (_jspx_meth_kk_005fmsg_005f5(_jspx_page_context))
        return;
      out.write("</h2>\n");
      out.write("\t\t\t\t\t\t<div id=\"price-range-slider\"></div>\n");
      out.write("\t\t\t\t\t\t<div id=\"amount\"></div>\n");
      out.write("\t    \t\t\t</div>\n");
      out.write("\t\t\t\t\t<form action=\"FilterSearchByPrice.action\" id='priceFilterForm' method=\"post\">\n");
      out.write("\t\t\t\t\t\t<input id=\"priceFromStr\" name=\"priceFromStr\" type=\"hidden\"/>\n");
      out.write("\t\t\t\t\t\t<input id=\"priceToStr\" name=\"priceToStr\" type=\"hidden\"/>\n");
      out.write("\t\t\t\t\t\t<input id=\"timestamp\" name=\"timestamp\" type=\"hidden\" value=\"");
      out.print(prodMgr.getProdTimestamp());
      out.write("\"/>\n");
      out.write("\t\t\t\t\t\t<input id=\"taxMultiplier\" name=\"taxMultiplier\" type=\"hidden\" value=\"");
      out.print(prodMgr.getTaxMultiplier());
      out.write("\"/>\n");
      out.write("\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t");
 } 
      out.write("\n");
      out.write("\t\t\t\t");
if (haveFacets){ 
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"side-menu-section\">\n");
      out.write("\t\t\t\t\t");
 for (int i = 0; i < prodMgr.getCurrentTagGroups().length; i++){ 
      out.write("\n");
      out.write("\t\t\t\t\t\t");
 com.konakart.appif.TagGroupIf tagGroup = prodMgr.getCurrentTagGroups()[i];
      out.write("\n");
      out.write("\t\t\t\t\t\t<h2>");
      out.print(tagGroup.getName());
      out.write("</h2>\n");
      out.write("\t\t\t\t\t\t");
if (tagGroup.getTags() != null && tagGroup.getTags().length > 0){ 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t");
 for (int j = 0; j < tagGroup.getTags().length; j++){ 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t");
 com.konakart.appif.TagIf tag = tagGroup.getTags()[j];
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t");
String name = (useSolr)? kkEng.getMsg(tag.getName()): tag.getName(); 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t");
if ( tag.isSelected()) { 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href='");
      out.print("FilterSearchByTags.action?tagId="+tag.getId()+"&t="+prodMgr.getProdTimestamp());
      out.write("'><span class=\"selected\"></span>");
      out.print(name+" ("+tag.getNumProducts()+")");
      out.write("</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t");
 } else { 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href='");
      out.print("FilterSearchByTags.action?tagId="+tag.getId()+"&t="+prodMgr.getProdTimestamp());
      out.write("'><span class=\"not-selected\"></span>");
      out.print(name+" ("+tag.getNumProducts()+")");
      out.write("</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t");
 } 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t");
 } 
      out.write("\n");
      out.write("\t\t\t");
}
      out.write("\t\t    \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t</div>\n");
      out.write(" \n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_kk_005fmsg_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f0 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f0.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f0.setParent(null);
    // /WEB-INF/jsp/Facets.jsp(71,9) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f0.setKey("facet.tile.categories");
    int _jspx_eval_kk_005fmsg_005f0 = _jspx_th_kk_005fmsg_005f0.doStartTag();
    if (_jspx_th_kk_005fmsg_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f0);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f1 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f1.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f1.setParent(null);
    // /WEB-INF/jsp/Facets.jsp(104,6) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f1.setKey("facet.tile.refine.search");
    int _jspx_eval_kk_005fmsg_005f1 = _jspx_th_kk_005fmsg_005f1.doStartTag();
    if (_jspx_th_kk_005fmsg_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f1);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f2 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f2.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f2.setParent(null);
    // /WEB-INF/jsp/Facets.jsp(110,147) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f2.setKey("products.body.clear.filters");
    int _jspx_eval_kk_005fmsg_005f2 = _jspx_th_kk_005fmsg_005f2.doStartTag();
    if (_jspx_th_kk_005fmsg_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f2);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f3 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f3.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f3.setParent(null);
    // /WEB-INF/jsp/Facets.jsp(115,10) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f3.setKey("facet.tile.manufacturers");
    int _jspx_eval_kk_005fmsg_005f3 = _jspx_th_kk_005fmsg_005f3.doStartTag();
    if (_jspx_th_kk_005fmsg_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f3);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f4 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f4.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f4.setParent(null);
    // /WEB-INF/jsp/Facets.jsp(131,10) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f4.setKey("facet.tile.price.range");
    int _jspx_eval_kk_005fmsg_005f4 = _jspx_th_kk_005fmsg_005f4.doStartTag();
    if (_jspx_th_kk_005fmsg_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f4);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f5 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f5.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f5.setParent(null);
    // /WEB-INF/jsp/Facets.jsp(154,13) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f5.setKey("common.price");
    int _jspx_eval_kk_005fmsg_005f5 = _jspx_th_kk_005fmsg_005f5.doStartTag();
    if (_jspx_th_kk_005fmsg_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f5);
    return false;
  }
}
